# See https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# and https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-static-site-generators-with-nodejs :
---
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout
      - uses: azure/setup-helm@v4 # https://github.com/azure/setup-helm
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package and index Helm chart
        run: |
          set -o errexit -o nounset -o pipefail
          helm package . --destination dist
          helm push ./dist/*.tgz oci://ghcr.io/${{ github.repository }}
      - uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: dist
on:
  push:
    # Publish semver tags as releases:
    tags: [ 'v*.*.*' ]
